import { useState } from "react";

type Props = { isSubmitting: boolean; onClose: () => void; onSubmit: (currentPassword: string, newPassword: string) => Promise<void> };

function ChangePasswordForm({ isSubmitting, onClose, onSubmit }: Props) {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!currentPassword.trim()) return setError("Current password is required."); if (newPassword.trim().length < 8 || newPassword.length > 128) return setError("New password must be between 8 and 128 characters."); if (newPassword !== confirmPassword) return setError("New passwords do not match."); if (newPassword === currentPassword) return setError("New password must differ from your current password."); try { setError(null); await onSubmit(currentPassword, newPassword); } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : "We couldn't change your password."); } };
  return <div className="fixed inset-0 z-50 flex items-end bg-black/40 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="change-password-title"><form onSubmit={submit} className="w-full rounded-t-lg bg-[var(--surface)] p-5 sm:max-w-md sm:rounded-lg"><div className="mb-5 flex justify-between gap-4"><h2 id="change-password-title" className="text-lg font-semibold">Change password</h2><button type="button" onClick={onClose} disabled={isSubmitting} className="text-sm text-[var(--text-secondary)]">Close</button></div>{error && <p className="mb-4 rounded-md bg-red-50 p-3 text-sm text-[var(--expense)]">{error}</p>}<div className="space-y-4"><label className="block text-sm font-medium">Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} maxLength={128} className="mt-1 w-full rounded-md border border-[var(--border)] p-2 font-normal" /></label><label className="block text-sm font-medium">New password<input type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={8} maxLength={128} className="mt-1 w-full rounded-md border border-[var(--border)] p-2 font-normal" /></label><label className="block text-sm font-medium">Confirm new password<input type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} minLength={8} maxLength={128} className="mt-1 w-full rounded-md border border-[var(--border)] p-2 font-normal" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={isSubmitting} className="rounded-md border border-[var(--border)] px-4 py-2 text-sm">Cancel</button><button type="submit" disabled={isSubmitting} className="rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{isSubmitting ? "Changing..." : "Change password"}</button></div></form></div>;
}

export default ChangePasswordForm;